<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="MAIN" Id="{c51feae6-2cfd-4c89-b598-db2fc7fdb705}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbFIFOTest : FB_FIFOTest;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbFIFOTest();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>